[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lst-restaking = "4ejcBdrPJUQ485bTxVfNQH42zTdN4i6gpyxPAGQkyfg9"
native-restaking = "2FP3X2ky9aDf9F9WXbrz76vcC7PgTAUDFqkwrkiZuJNB"
solana_restaking = "FDNc8vxUQ695kg1dUfPTuPHzwwWyrS6DBvdtj9F3y6yV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/scarecrow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
