[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lst-restaking = "DMKWjKA56Wk3stpGjkMJ6YYDS58TvowZEShdg3AYiH17"
native-restaking = "AtfUbXniQddbR3DVetG2xJz7Hnyg8geNECRrDdnLsYZ5"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
# cluster = "Devnet"
cluster = "https://solana-devnet.g.alchemy.com/v2/aX4Snr1_FQhgbX_QtH-PapYe1_VRTfQZ"
wallet = ".keys/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/Initialize.test.ts"

addToken = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/AddWhiteList.test.ts"
addTokenAgain = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/AddWhiteListFailure.test.ts"
deactivateToken = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/DeactivateWhiteList.test.ts"
deactivateNotInWhiteListToken= "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/DeactivateWhiteListFailure.test.ts"

transferOwnership = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/TransferOwnership.test.ts"
transferOwnershipFailure = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/TransferOwnershipFailure.test.ts"

accept = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/Accept.test.ts"
acceptFailure = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/AcceptFailure.test.ts"

#############
deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/Deposit.test.ts"
withdrawPrincipal = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/WithdrawPrincipalFromExocore.test.ts"
withdrawReward = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/WithdrawRewardFromExocore.test.ts"
delegateTo = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/DelegateTo.test.ts"
depositThenDelegateTo = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/DepositThenDelegateTo.test.ts"
