[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lst-restaking = "68av2QdR1k1QeaxsJwjiB16QHXDhTuaS14tyTNM3MgHX"
native-restaking = "AtfUbXniQddbR3DVetG2xJz7Hnyg8geNECRrDdnLsYZ5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/scarecrow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
